### ISSUE TITLE
uciqe代码有问题

### ISSUE THREAD

**Issue by deepxzy** [xueleichen/PSNR-SSIM-UCIQE-UIQM-Python#3]
nevaluate 
第37行，conl = np.mean(isl[::top])-np.mean(sl[::top])，
应改为conl = np.mean(isl[:top])-np.mean(sl[:top])
::top是隔top个取一个的意思，:top才是取前top个的意思

**Comment by xueleichen** [comment]
你好，这儿的确写错了，已更正，谢谢！
